### PR TITLE
remove access comma

### PR DESCRIPTION
**Pull request by seriousadi**
removed some access commas which were in end of the element of a list and something like that

### CODE REVIEW

**Comment by berendt** [comment]
That's not necessary.

**Comment by seriousadi** [comment]
common man this could have bin my first accepted pull request 😂😂

**Comment by seriousadi** [comment]
That wasn't random we do not put comma after last element of list because it can cause bugs like this
l=["a","d",]
print(len(l))
and in this there is comma after last element of list and the output will be3 and it can cause error and there was a lot of commas like this

**Comment by seriousadi** [comment]
you will be expecting 2 but output will be 3 and after working on this code more it will be really hard to point out the thing which is causing it

**Pull request closed without merging**
